spring:
  application:
    name: metricsproducer
  kafka:
    producer:
      bootstrap-servers: "localhost:9092"

management:
  endpoints:
    web:
      exposure:
        include: metrics

server:
  port: 8080

kafka:
  topic:
    metrics-topic: "metrics-topic"